packages:
  - apps/*
  - packages/adapters/*
  - packages/channels/*
  - packages/plugins/*
  - packages/*
overrides:
  array-includes: npm:@nolyfill/array-includes@latest
  array.prototype.flat: npm:@nolyfill/array.prototype.flat@latest
  array.prototype.flatmap: npm:@nolyfill/array.prototype.flatmap@latest
  array.prototype.tosorted: npm:@nolyfill/array.prototype.tosorted@latest
  es-iterator-helpers: npm:@nolyfill/es-iterator-helpers@latest
  function-bind: npm:@nolyfill/function-bind@latest
  generator-function: 1.0.0
  is-generator-function: 1.0.7
  object.assign: npm:@nolyfill/object.assign@latest
  object.entries: npm:@nolyfill/object.entries@latest
  object.fromentries: npm:@nolyfill/object.fromentries@latest
  object.hasown: npm:@nolyfill/object.hasown@latest
  object.values: npm:@nolyfill/object.values@latest
  string.prototype.matchall: npm:@nolyfill/string.prototype.matchall@latest
  unbox-primitive: npm:@nolyfill/unbox-primitive@latest
onlyBuiltDependencies:
  - '@swc/core'
  - '@parcel/watcher'
  - electron
  - electron-winstaller
  - esbuild
  - node-pty
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@vscode/vsce-sign': true
  dprint: true
  electron: true
  electron-winstaller: true
  esbuild: true
  keytar: true
  node-pty: true
  protobufjs: true
