export const CODEX_APP_SERVER_RUNTIME_DRIVER_ID = 'codex.app-server'
export const RUNTIME_BROKER_CALLBACK_URL_ENV = '__ONEWORKS_RUNTIME_BROKER_CALLBACK_URL__'
export const RUNTIME_BROKER_CALLBACK_TOKEN_ENV = '__ONEWORKS_RUNTIME_BROKER_CALLBACK_TOKEN__'
