/* eslint-disable max-lines -- dev-only fixture keeps a branchy history sample readable in one place. */
import type { ChatHistoryTimelineNode } from '#~/components/chat/history-timeline'

type TimelineNodeFixture = Omit<ChatHistoryTimelineNode, 'info'> & {
  activeChildId?: string
  branchId?: string
  childIds?: string[]
  depth: number
  forkCount?: number
  isOnActivePath?: boolean
  kind: ChatHistoryTimelineNode['info']['kind']
  lane?: number
  marks?: ChatHistoryTimelineNode['info']['marks']
  parentId?: string
  railMarker?: boolean
  siblingCount?: number
  siblingIndex?: number
  status?: ChatHistoryTimelineNode['info']['status']
}

const completeStatus = {
  label: 'Complete',
  state: 'complete'
} satisfies NonNullable<ChatHistoryTimelineNode['info']['status']>

const createTimelineNode = ({
  activeChildId,
  branchId = 'main',
  childIds = [],
  depth,
  forkCount,
  isOnActivePath = true,
  kind,
  lane = 0,
  marks,
  parentId,
  railMarker,
  siblingCount = 1,
  siblingIndex = 0,
  status = completeStatus,
  ...node
}: TimelineNodeFixture): ChatHistoryTimelineNode => ({
  ...node,
  info: {
    graph: {
      ...(activeChildId == null ? {} : { activeChildId }),
      branchId,
      childIds,
      depth,
      ...(forkCount == null ? {} : { forkCount }),
      isOnActivePath,
      lane,
      ...(parentId == null ? {} : { parentId }),
      siblingCount,
      siblingIndex
    },
    kind,
    ...(marks == null ? {} : { marks }),
    ...(railMarker == null ? {} : { rail: { marker: railMarker } }),
    status
  }
})

// Timeline nodes are conversation anchors, not AI work logs. If the assistant emits
// several ordinary visible messages in a row, only the final conclusion becomes the timeline node.
export const chatTimelineNodes: ChatHistoryTimelineNode[] = [
  createTimelineNode({
    id: 'u-brief',
    messageId: 'msg-01',
    title: 'Core timeline shape with a much longer branch metadata label that should truncate gracefully',
    description: 'Keep the right side rail focused on user turns and final answer anchors.',
    timestamp: '10:12',
    kind: 'question',
    activeChildId: 'a-brief-final',
    branchId: 'main-long-context-branch-with-review-retry-state-and-extra-diagnostic-metadata',
    childIds: ['a-brief-final'],
    depth: 0,
    marks: { starred: true }
  }),
  createTimelineNode({
    id: 'a-brief-final',
    messageId: 'msg-03',
    title: 'Linear rail proposal',
    description: 'Final AI message in this answer group becomes the rail anchor.',
    timestamp: '10:14',
    kind: 'answer',
    activeChildId: 'u-node-object',
    childIds: ['u-node-object', 'u-rail-only'],
    depth: 1,
    forkCount: 2,
    parentId: 'u-brief'
  }),
  createTimelineNode({
    id: 'u-node-object',
    messageId: 'msg-04',
    title: 'Message node object',
    description: 'Fold pinned and starred into a message node info object with branch metadata.',
    timestamp: '10:16',
    kind: 'question',
    activeChildId: 'a-node-object',
    childIds: ['a-node-object'],
    depth: 3,
    parentId: 'a-brief-final',
    siblingCount: 2,
    marks: { pinned: true }
  }),
  createTimelineNode({
    id: 'u-rail-only',
    messageId: 'msg-04b',
    title: 'Rail only branch',
    description: 'Alternative question branch that keeps the UI as a simple point rail.',
    timestamp: '10:17',
    kind: 'question',
    activeChildId: 'a-rail-only',
    branchId: 'rail-only',
    childIds: ['a-rail-only'],
    depth: 3,
    isOnActivePath: false,
    lane: 1,
    parentId: 'a-brief-final',
    siblingCount: 2,
    siblingIndex: 1
  }),
  createTimelineNode({
    id: 'a-rail-only',
    messageId: 'msg-05b',
    title: 'Minimal rail variation',
    description: 'This branch preserves the conversation but hides structural forks.',
    timestamp: '10:18',
    kind: 'answer',
    branchId: 'rail-only',
    depth: 4,
    isOnActivePath: false,
    lane: 1,
    parentId: 'u-rail-only',
    status: { label: 'Archived', state: 'complete' }
  }),
  createTimelineNode({
    id: 'a-node-object',
    messageId: 'msg-05',
    title: 'Branch-aware model',
    description: 'A single AI reply is also registered because it is the final answer message.',
    timestamp: '10:20',
    kind: 'answer',
    activeChildId: 'u-git-graph',
    childIds: ['u-git-graph'],
    depth: 4,
    parentId: 'u-node-object'
  }),
  createTimelineNode({
    id: 'u-git-graph',
    messageId: 'msg-06',
    title: 'Git graph view',
    description:
      'User message includes multiple lines:\nShow branch lanes in the expanded panel.\nKeep the compact rail quiet unless a node is important.',
    timestamp: '10:26',
    kind: 'question',
    activeChildId: 'u-git-layout-note',
    childIds: [
      'u-git-layout-note',
      'u-compact-branch',
      'u-split-branch',
      'u-compare-branch',
      'u-debug-branch'
    ],
    depth: 5,
    forkCount: 5,
    parentId: 'a-node-object',
    marks: { pinned: true, starred: true }
  }),
  createTimelineNode({
    id: 'u-git-layout-note',
    messageId: 'msg-06a',
    title: 'One more constraint before AI answers',
    description: 'User adds a second note without waiting for the assistant: keep the graph drawer compact.',
    timestamp: '10:27',
    kind: 'question',
    activeChildId: 'u-git-scroll-note',
    childIds: ['u-git-scroll-note'],
    depth: 6,
    parentId: 'u-git-graph',
    siblingCount: 5
  }),
  createTimelineNode({
    id: 'u-git-scroll-note',
    messageId: 'msg-06a2',
    title: 'And make scroll sync obvious',
    description: 'A third user message lands before the assistant replies, matching real rapid-fire clarification.',
    timestamp: '10:27',
    kind: 'question',
    activeChildId: 'a-git-graph-final',
    childIds: ['a-git-graph-final'],
    depth: 7,
    parentId: 'u-git-layout-note'
  }),
  createTimelineNode({
    id: 'u-compact-branch',
    messageId: 'msg-06b',
    title: 'Compact branch view',
    description: 'A side path that keeps only turn-level anchors visible in the graph.',
    timestamp: '10:27',
    kind: 'question',
    activeChildId: 'a-compact-branch',
    branchId: 'compact',
    childIds: ['a-compact-branch'],
    depth: 6,
    isOnActivePath: false,
    lane: 1,
    parentId: 'u-git-graph',
    siblingCount: 5,
    siblingIndex: 1,
    status: { label: 'Complete', state: 'complete' }
  }),
  createTimelineNode({
    id: 'a-compact-branch',
    messageId: 'msg-07b',
    title: 'Turn anchors only',
    description: 'This branch tests whether the tree can stay readable with fewer labels.',
    timestamp: '10:28',
    kind: 'answer',
    branchId: 'compact',
    depth: 7,
    isOnActivePath: false,
    lane: 1,
    parentId: 'u-compact-branch'
  }),
  createTimelineNode({
    id: 'u-split-branch',
    messageId: 'msg-06c',
    title: 'Split panel branch',
    description: 'A second side path for comparing a wider list beside the graph lane.',
    timestamp: '10:28',
    kind: 'question',
    activeChildId: 'a-split-branch',
    branchId: 'split',
    childIds: ['a-split-branch'],
    depth: 6,
    isOnActivePath: false,
    lane: 2,
    parentId: 'u-git-graph',
    siblingCount: 5,
    siblingIndex: 2,
    status: { label: 'Complete', state: 'complete' }
  }),
  createTimelineNode({
    id: 'a-split-branch',
    messageId: 'msg-07c',
    title: 'Side-by-side option',
    description: 'The alternate branch keeps cards wider and shifts the graph into a gutter.',
    timestamp: '10:29',
    kind: 'answer',
    branchId: 'split',
    depth: 7,
    isOnActivePath: false,
    lane: 2,
    parentId: 'u-split-branch'
  }),
  createTimelineNode({
    id: 'u-compare-branch',
    messageId: 'msg-06d',
    title: 'Comparison branch',
    description: 'A side path for comparing dense graph, split panel, and compact rail layouts.',
    timestamp: '10:29',
    kind: 'question',
    activeChildId: 'a-compare-branch',
    branchId: 'compare',
    childIds: ['a-compare-branch'],
    depth: 6,
    isOnActivePath: false,
    lane: 3,
    parentId: 'u-git-graph',
    siblingCount: 5,
    siblingIndex: 3,
    marks: { pinned: true },
    status: { label: 'Waiting', state: 'waiting' }
  }),
  createTimelineNode({
    id: 'a-compare-branch',
    messageId: 'msg-07d',
    title: 'Dense comparison option',
    description: 'This branch shows the densest graph treatment with more sibling lanes.',
    timestamp: '10:30',
    kind: 'answer',
    activeChildId: 'u-compare-followup',
    branchId: 'compare',
    childIds: ['u-compare-followup'],
    depth: 7,
    isOnActivePath: false,
    lane: 3,
    parentId: 'u-compare-branch',
    status: { label: 'Complete', state: 'complete' }
  }),
  createTimelineNode({
    id: 'u-compare-followup',
    messageId: 'msg-08d',
    title: 'Continue dense branch for a few more turns',
    description: 'The user keeps exploring this fork instead of returning to the main path.',
    timestamp: '10:32',
    kind: 'question',
    activeChildId: 'a-compare-scroll-pass',
    branchId: 'compare',
    childIds: ['a-compare-scroll-pass'],
    depth: 8,
    isOnActivePath: false,
    lane: 3,
    parentId: 'a-compare-branch'
  }),
  createTimelineNode({
    id: 'a-compare-scroll-pass',
    messageId: 'msg-09d',
    title: 'Multiline answer checkpoint',
    description:
      'AI response verifies a longer message shape:\n- compare branch stays readable\n- nested forks still align\n- previews clamp after two lines',
    timestamp: '10:34',
    kind: 'answer',
    activeChildId: 'u-compare-nested-fork',
    branchId: 'compare',
    childIds: ['u-compare-nested-fork'],
    depth: 9,
    isOnActivePath: false,
    lane: 3,
    parentId: 'u-compare-followup',
    status: { label: 'Complete', state: 'complete' }
  }),
  createTimelineNode({
    id: 'u-compare-nested-fork',
    messageId: 'msg-10d',
    title: 'Fork inside the comparison branch',
    description: 'A second fork appears after the user has already chatted for a while.',
    timestamp: '10:37',
    kind: 'question',
    activeChildId: 'a-compare-main-resolution',
    branchId: 'compare',
    childIds: [
      'a-compare-main-resolution',
      'u-compare-alt-density',
      'u-compare-alt-summary'
    ],
    depth: 10,
    forkCount: 3,
    isOnActivePath: false,
    lane: 3,
    marks: { starred: true },
    parentId: 'a-compare-scroll-pass'
  }),
  createTimelineNode({
    id: 'u-compare-alt-density',
    messageId: 'msg-10d-b',
    title: 'Try an even denser branch',
    description: 'Side branch that squeezes extra anchors into the same expanded graph.',
    timestamp: '10:38',
    kind: 'question',
    activeChildId: 'a-compare-alt-density',
    branchId: 'compare-dense',
    childIds: ['a-compare-alt-density'],
    depth: 11,
    isOnActivePath: false,
    lane: 4,
    parentId: 'u-compare-nested-fork',
    siblingCount: 3,
    siblingIndex: 1,
    status: { label: 'Waiting', state: 'waiting' }
  }),
  createTimelineNode({
    id: 'a-compare-alt-density',
    messageId: 'msg-11d-b',
    title: 'Dense lane alternative',
    description: 'This answer keeps the graph compact but makes the card list harder to scan.',
    timestamp: '10:40',
    kind: 'answer',
    branchId: 'compare-dense',
    depth: 12,
    isOnActivePath: false,
    lane: 4,
    parentId: 'u-compare-alt-density',
    status: { label: 'Paused', state: 'waiting' }
  }),
  createTimelineNode({
    id: 'u-compare-alt-summary',
    messageId: 'msg-10d-c',
    title: 'Summarize this branch instead',
    description: 'Another side path tests a short offshoot from a long forked conversation.',
    timestamp: '10:39',
    kind: 'question',
    activeChildId: 'a-compare-alt-summary',
    branchId: 'compare-summary',
    childIds: ['a-compare-alt-summary'],
    depth: 11,
    isOnActivePath: false,
    lane: 5,
    parentId: 'u-compare-nested-fork',
    siblingCount: 3,
    siblingIndex: 2
  }),
  createTimelineNode({
    id: 'a-compare-alt-summary',
    messageId: 'msg-11d-c',
    title: 'Branch summary',
    description: 'The summary branch ends quickly after capturing the design tradeoffs.',
    timestamp: '10:41',
    kind: 'answer',
    branchId: 'compare-summary',
    depth: 12,
    isOnActivePath: false,
    lane: 5,
    parentId: 'u-compare-alt-summary'
  }),
  createTimelineNode({
    id: 'a-compare-main-resolution',
    messageId: 'msg-11d',
    title: 'Keep the compare branch readable',
    description: 'Main answer for the nested fork keeps cards aligned with the selected path.',
    timestamp: '10:42',
    kind: 'answer',
    activeChildId: 'u-compare-wrap-up',
    branchId: 'compare',
    childIds: ['u-compare-wrap-up'],
    depth: 11,
    isOnActivePath: false,
    lane: 3,
    parentId: 'u-compare-nested-fork',
    siblingCount: 3
  }),
  createTimelineNode({
    id: 'u-compare-wrap-up',
    messageId: 'msg-12d',
    title: 'Wrap up the long fork',
    description: 'User returns to the selected compare route after testing nested alternatives.',
    timestamp: '10:45',
    kind: 'question',
    activeChildId: 'a-compare-wrap-up',
    branchId: 'compare',
    childIds: ['a-compare-wrap-up'],
    depth: 12,
    isOnActivePath: false,
    lane: 3,
    parentId: 'a-compare-main-resolution',
    marks: { pinned: true }
  }),
  createTimelineNode({
    id: 'a-compare-wrap-up',
    messageId: 'msg-13d',
    title: 'Long fork final answer',
    description: 'Final answer in the fork becomes a strong rail marker when this branch is active.',
    timestamp: '10:48',
    kind: 'answer',
    branchId: 'compare',
    depth: 13,
    isOnActivePath: false,
    lane: 3,
    parentId: 'u-compare-wrap-up'
  }),
  createTimelineNode({
    id: 'u-debug-branch',
    messageId: 'msg-06e',
    title: 'Debug branch labels',
    description: 'A fourth side path for stress-testing labels, badges, and hover previews.',
    timestamp: '10:30',
    kind: 'question',
    activeChildId: 'a-debug-branch',
    branchId: 'debug',
    childIds: ['a-debug-branch'],
    depth: 6,
    isOnActivePath: false,
    lane: 4,
    parentId: 'u-git-graph',
    siblingCount: 5,
    siblingIndex: 4,
    status: { label: 'Waiting', state: 'waiting' }
  }),
  createTimelineNode({
    id: 'a-debug-branch',
    messageId: 'msg-07e',
    title: 'Label stress pass',
    description: 'This branch keeps the same parent point while exercising far-side lanes.',
    timestamp: '10:31',
    kind: 'answer',
    branchId: 'debug',
    depth: 7,
    isOnActivePath: false,
    lane: 4,
    parentId: 'u-debug-branch',
    status: { label: 'Waiting', state: 'waiting' }
  }),
  createTimelineNode({
    id: 'a-git-graph-final',
    messageId: 'msg-09',
    title: 'Branch graph interaction',
    description: 'Final AI message in the group syncs graph selection and becomes the rail marker.',
    timestamp: '10:33',
    kind: 'answer',
    activeChildId: 'u-component-lab',
    childIds: ['u-component-lab'],
    depth: 8,
    parentId: 'u-git-scroll-note'
  }),
  createTimelineNode({
    id: 'u-component-lab',
    messageId: 'msg-10',
    title: 'Multiline user note',
    description:
      'User message spans multiple lines:\nPlease keep the drawer aligned with the rail.\nAlso make sure branch switching and collapsed markers still work.',
    timestamp: '10:36',
    kind: 'question',
    activeChildId: 'a-scroll-validation',
    childIds: ['a-scroll-validation'],
    depth: 9,
    parentId: 'a-git-graph-final'
  }),
  createTimelineNode({
    id: 'a-scroll-validation',
    messageId: 'msg-11b',
    title: 'Scrollable history conclusion',
    description: 'Final conclusion for the assistant burst; the earlier visible AI note stays out of the timeline.',
    timestamp: '10:40',
    kind: 'answer',
    activeChildId: 'u-scroll-density',
    childIds: ['u-scroll-density'],
    depth: 10,
    parentId: 'u-component-lab'
  }),
  createTimelineNode({
    id: 'u-scroll-density',
    messageId: 'msg-12',
    title: 'Long history density',
    description: 'Make the prototype demonstrate scroll position and compact rail rhythm.',
    timestamp: '10:42',
    kind: 'question',
    activeChildId: 'a-anchor-map-final',
    childIds: ['a-anchor-map-final'],
    depth: 11,
    parentId: 'a-scroll-validation'
  }),
  createTimelineNode({
    id: 'a-anchor-map-final',
    messageId: 'msg-14',
    title: 'Viewport sync adapter',
    description: 'Final AI message defines how the host controls scroll and selection.',
    timestamp: '10:45',
    kind: 'answer',
    activeChildId: 'u-sync-window',
    childIds: ['u-sync-window'],
    depth: 12,
    parentId: 'u-scroll-density'
  }),
  createTimelineNode({
    id: 'u-sync-window',
    messageId: 'msg-15',
    title: 'Viewport sync',
    description: 'The rail should highlight the closest registered message as the list scrolls.',
    timestamp: '10:47',
    kind: 'question',
    activeChildId: 'a-sync-window',
    childIds: ['a-sync-window'],
    depth: 13,
    parentId: 'a-anchor-map-final',
    marks: { starred: true },
    status: { label: 'Ask User Question', state: 'ask-user' }
  }),
  createTimelineNode({
    id: 'a-sync-window',
    messageId: 'msg-16',
    title: 'Current turn heuristic',
    description: 'IntersectionObserver can drive selectedNodeId without reading message DOM content.',
    timestamp: '10:51',
    kind: 'answer',
    activeChildId: 'u-branch-badge',
    childIds: ['u-branch-badge'],
    depth: 14,
    parentId: 'u-sync-window'
  }),
  createTimelineNode({
    id: 'u-branch-badge',
    messageId: 'msg-17',
    title: 'Late branch badge',
    description: 'A later fork keeps the compact rail honest when a thread has multiple forks.',
    timestamp: '10:54',
    kind: 'question',
    activeChildId: 'a-branch-badge',
    childIds: ['a-branch-badge', 'u-late-branch'],
    depth: 15,
    forkCount: 2,
    parentId: 'a-sync-window',
    marks: { pinned: true }
  }),
  createTimelineNode({
    id: 'u-late-branch',
    messageId: 'msg-17b',
    title: 'Dense side path',
    description: 'A side branch for testing how late forks appear in the expanded graph.',
    timestamp: '10:55',
    kind: 'question',
    activeChildId: 'a-late-branch',
    branchId: 'late-density',
    childIds: ['a-late-branch'],
    depth: 16,
    isOnActivePath: false,
    lane: 2,
    parentId: 'u-branch-badge',
    siblingCount: 2,
    siblingIndex: 1,
    status: { label: 'Waiting', state: 'waiting' }
  }),
  createTimelineNode({
    id: 'a-late-branch',
    messageId: 'msg-18b',
    title: 'Alternate scroll treatment',
    description: 'This branch experiments with hiding labels until hover.',
    timestamp: '10:56',
    kind: 'answer',
    branchId: 'late-density',
    depth: 17,
    isOnActivePath: false,
    lane: 2,
    parentId: 'u-late-branch',
    status: { label: 'Paused', state: 'waiting' }
  }),
  createTimelineNode({
    id: 'a-branch-badge',
    messageId: 'msg-19',
    title: 'Badge stays compact',
    description: 'Fork count is shown as a small badge without widening the scrollbar-like rail.',
    timestamp: '10:58',
    kind: 'answer',
    activeChildId: 'u-selection-sync',
    childIds: ['u-selection-sync'],
    depth: 16,
    parentId: 'u-branch-badge',
    siblingCount: 2
  }),
  createTimelineNode({
    id: 'u-selection-sync',
    messageId: 'msg-20',
    title: 'Selection sync',
    description: 'Clicking rail markers should select and scroll the host message into view.',
    timestamp: '11:02',
    kind: 'question',
    activeChildId: 'a-selection-sync',
    childIds: ['a-selection-sync'],
    depth: 17,
    parentId: 'a-branch-badge',
    status: { label: 'Permission Request', state: 'permission' }
  }),
  createTimelineNode({
    id: 'a-selection-sync',
    messageId: 'msg-21',
    title: 'Host-controlled scroll',
    description: 'The generic rail emits node selection; the chat host owns actual scrolling.',
    timestamp: '11:04',
    kind: 'answer',
    activeChildId: 'u-late-recall',
    childIds: ['u-late-recall'],
    depth: 18,
    parentId: 'u-selection-sync'
  }),
  createTimelineNode({
    id: 'u-late-recall',
    messageId: 'msg-22',
    title: 'Late recall marker',
    description: 'Pinned and starred metadata remains on the same node.info object.',
    timestamp: '11:08',
    kind: 'question',
    activeChildId: 'a-late-recall',
    childIds: ['a-late-recall'],
    depth: 19,
    parentId: 'a-selection-sync',
    marks: { pinned: true, starred: true }
  }),
  createTimelineNode({
    id: 'a-late-recall',
    messageId: 'msg-24',
    title: 'Long-thread polish',
    description: 'The compact rail keeps density low while the branch graph remains inspectable.',
    timestamp: '11:12',
    kind: 'answer',
    activeChildId: 'u-ready-component',
    childIds: ['u-ready-component'],
    depth: 20,
    parentId: 'u-late-recall'
  }),
  createTimelineNode({
    id: 'u-ready-component',
    messageId: 'msg-25',
    title: 'Wire this into chat history',
    description: 'User asks to connect the timeline UI to real chat history data.',
    timestamp: '11:15',
    kind: 'question',
    depth: 21,
    parentId: 'a-late-recall',
    status: { label: 'Running', state: 'running' }
  })
]

const chatTimelineHostMessageInserts = [
  {
    beforeNodeId: 'a-scroll-validation',
    messages: [
      {
        id: 'host-a-scroll-density',
        timelineNodeId: 'a-scroll-validation',
        isTimelineAnchor: false,
        title: 'Scrollable history pass',
        description: 'Assistant drafts the scroll treatment first, then follows with a final conclusion.',
        timestamp: '10:39',
        kind: 'answer' as const
      }
    ]
  }
]

export const smallTimelineNodes: ChatHistoryTimelineNode[] = [
  createTimelineNode({
    id: 'small-u-start',
    messageId: 'small-01',
    title: 'One question',
    description: 'Small data path should not collapse or look empty.',
    timestamp: '09:00',
    kind: 'question',
    activeChildId: 'small-a-final',
    childIds: ['small-a-final'],
    depth: 0,
    marks: { starred: true }
  }),
  createTimelineNode({
    id: 'small-a-final',
    messageId: 'small-03',
    title: 'Final answer',
    description: 'One question and the final AI reply, no internal draft node.',
    timestamp: '09:02',
    kind: 'answer',
    depth: 1,
    parentId: 'small-u-start'
  })
]

export const complexForkTimelineNodes: ChatHistoryTimelineNode[] = [
  createTimelineNode({
    id: 'cx-u-root',
    messageId: 'cx-01',
    title: 'Complex fork root',
    description: 'Start a compact but deeply branched conversation fixture.',
    timestamp: '12:00',
    kind: 'question',
    activeChildId: 'cx-a-scan',
    childIds: ['cx-a-scan'],
    depth: 0,
    marks: { starred: true }
  }),
  createTimelineNode({
    id: 'cx-a-scan',
    messageId: 'cx-02',
    title: 'Map possible paths',
    description: 'The answer identifies several directions before the user forks hard.',
    timestamp: '12:01',
    kind: 'answer',
    activeChildId: 'cx-u-router',
    childIds: ['cx-u-router'],
    depth: 1,
    parentId: 'cx-u-root'
  }),
  createTimelineNode({
    id: 'cx-u-router',
    messageId: 'cx-03',
    title: 'Fork into many directions',
    description:
      'User fans out aggressively:\nmain path, fast path, safe path, visual path, data path, risk path, local path, audit path.',
    timestamp: '12:04',
    kind: 'question',
    activeChildId: 'cx-a-main-start',
    childIds: [
      'cx-a-main-start',
      'cx-u-fast',
      'cx-u-safe',
      'cx-u-visual',
      'cx-u-data',
      'cx-u-risk',
      'cx-u-local',
      'cx-u-audit'
    ],
    depth: 2,
    forkCount: 8,
    marks: { pinned: true, starred: true },
    parentId: 'cx-a-scan'
  }),
  createTimelineNode({
    id: 'cx-a-main-start',
    messageId: 'cx-04',
    title: 'Main branch synthesis',
    description: 'Main route keeps moving while side branches remain inspectable.',
    timestamp: '12:06',
    kind: 'answer',
    activeChildId: 'cx-u-main-review',
    childIds: ['cx-u-main-review'],
    depth: 3,
    parentId: 'cx-u-router',
    siblingCount: 8
  }),
  createTimelineNode({
    id: 'cx-u-fast',
    messageId: 'cx-04b',
    title: 'Fast path',
    description: 'Shortest branch tests a narrow side path.',
    timestamp: '12:07',
    kind: 'question',
    activeChildId: 'cx-a-fast',
    branchId: 'fast',
    childIds: ['cx-a-fast'],
    depth: 3,
    isOnActivePath: false,
    lane: 1,
    parentId: 'cx-u-router',
    siblingCount: 8,
    siblingIndex: 1
  }),
  createTimelineNode({
    id: 'cx-u-safe',
    messageId: 'cx-04c',
    title: 'Safe path',
    description: 'Ask-user branch keeps priority status visible in the rail.',
    timestamp: '12:08',
    kind: 'question',
    activeChildId: 'cx-a-safe',
    branchId: 'safe',
    childIds: ['cx-a-safe'],
    depth: 3,
    isOnActivePath: false,
    lane: 2,
    parentId: 'cx-u-router',
    siblingCount: 8,
    siblingIndex: 2,
    status: { label: 'Ask User Question', state: 'ask-user' }
  }),
  createTimelineNode({
    id: 'cx-u-visual',
    messageId: 'cx-04d',
    title: 'Visual path with nested fork',
    description: 'This side branch forks again after the first answer.',
    timestamp: '12:09',
    kind: 'question',
    activeChildId: 'cx-a-visual-main',
    branchId: 'visual',
    childIds: ['cx-a-visual-main', 'cx-u-visual-dark', 'cx-u-visual-dense'],
    depth: 3,
    forkCount: 3,
    isOnActivePath: false,
    lane: 3,
    marks: { pinned: true },
    parentId: 'cx-u-router',
    siblingCount: 8,
    siblingIndex: 3
  }),
  createTimelineNode({
    id: 'cx-u-data',
    messageId: 'cx-04e',
    title: 'Data path',
    description: 'Error branch tests non-complete status styling.',
    timestamp: '12:10',
    kind: 'question',
    activeChildId: 'cx-a-data',
    branchId: 'data',
    childIds: ['cx-a-data'],
    depth: 3,
    isOnActivePath: false,
    lane: 4,
    parentId: 'cx-u-router',
    siblingCount: 8,
    siblingIndex: 4,
    status: { label: 'Error', state: 'error' }
  }),
  createTimelineNode({
    id: 'cx-u-risk',
    messageId: 'cx-04f',
    title: 'Risk path',
    description: 'Pinned late branch tests marker priority under heavy branching.',
    timestamp: '12:11',
    kind: 'question',
    activeChildId: 'cx-a-risk',
    branchId: 'risk',
    childIds: ['cx-a-risk'],
    depth: 3,
    isOnActivePath: false,
    lane: 5,
    marks: { starred: true },
    parentId: 'cx-u-router',
    siblingCount: 8,
    siblingIndex: 5
  }),
  createTimelineNode({
    id: 'cx-u-local',
    messageId: 'cx-04g',
    title: 'Local path',
    description: 'Permission branch exercises a user-intervention status.',
    timestamp: '12:12',
    kind: 'question',
    activeChildId: 'cx-a-local',
    branchId: 'local',
    childIds: ['cx-a-local'],
    depth: 3,
    isOnActivePath: false,
    lane: 6,
    parentId: 'cx-u-router',
    siblingCount: 8,
    siblingIndex: 6,
    status: { label: 'Permission Request', state: 'permission' }
  }),
  createTimelineNode({
    id: 'cx-u-audit',
    messageId: 'cx-04h',
    title: 'Audit path',
    description: 'Farthest lane verifies graph width and right-side alignment.',
    timestamp: '12:13',
    kind: 'question',
    activeChildId: 'cx-a-audit',
    branchId: 'audit',
    childIds: ['cx-a-audit'],
    depth: 3,
    isOnActivePath: false,
    lane: 7,
    parentId: 'cx-u-router',
    siblingCount: 8,
    siblingIndex: 7
  }),
  createTimelineNode({
    id: 'cx-a-fast',
    messageId: 'cx-05b',
    title: 'Fast answer',
    description: 'Ends immediately.',
    timestamp: '12:14',
    kind: 'answer',
    branchId: 'fast',
    depth: 4,
    isOnActivePath: false,
    lane: 1,
    parentId: 'cx-u-fast'
  }),
  createTimelineNode({
    id: 'cx-a-safe',
    messageId: 'cx-05c',
    title: 'Safe answer',
    description: 'Still waiting for confirmation.',
    timestamp: '12:15',
    kind: 'answer',
    branchId: 'safe',
    depth: 4,
    isOnActivePath: false,
    lane: 2,
    parentId: 'cx-u-safe',
    status: { label: 'Waiting', state: 'waiting' }
  }),
  createTimelineNode({
    id: 'cx-a-visual-main',
    messageId: 'cx-05d',
    title: 'Visual main answer',
    description: 'Primary visual branch continues beyond the nested fork point.',
    timestamp: '12:16',
    kind: 'answer',
    activeChildId: 'cx-u-visual-wrap',
    branchId: 'visual',
    childIds: ['cx-u-visual-wrap'],
    depth: 4,
    isOnActivePath: false,
    lane: 3,
    parentId: 'cx-u-visual',
    siblingCount: 3
  }),
  createTimelineNode({
    id: 'cx-a-data',
    messageId: 'cx-05e',
    title: 'Data answer failed',
    description: 'Represents a failed answer node on a side path.',
    timestamp: '12:17',
    kind: 'answer',
    branchId: 'data',
    depth: 4,
    isOnActivePath: false,
    lane: 4,
    parentId: 'cx-u-data',
    status: { label: 'Error', state: 'error' }
  }),
  createTimelineNode({
    id: 'cx-a-risk',
    messageId: 'cx-05f',
    title: 'Risk answer',
    description: 'Short answer with a starred parent.',
    timestamp: '12:18',
    kind: 'answer',
    branchId: 'risk',
    depth: 4,
    isOnActivePath: false,
    lane: 5,
    parentId: 'cx-u-risk'
  }),
  createTimelineNode({
    id: 'cx-a-local',
    messageId: 'cx-05g',
    title: 'Local answer still running',
    description: 'Long-lived running side path.',
    timestamp: '12:19',
    kind: 'answer',
    branchId: 'local',
    depth: 4,
    isOnActivePath: false,
    lane: 6,
    parentId: 'cx-u-local',
    status: { label: 'Running', state: 'running' }
  }),
  createTimelineNode({
    id: 'cx-a-audit',
    messageId: 'cx-05h',
    title: 'Audit answer',
    description: 'Farthest lane answer.',
    timestamp: '12:20',
    kind: 'answer',
    branchId: 'audit',
    depth: 4,
    isOnActivePath: false,
    lane: 7,
    parentId: 'cx-u-audit'
  }),
  createTimelineNode({
    id: 'cx-u-main-review',
    messageId: 'cx-05',
    title: 'Review main branch',
    description: 'Main branch continues through a normal question.',
    timestamp: '12:21',
    kind: 'question',
    activeChildId: 'cx-a-main-result',
    childIds: ['cx-a-main-result'],
    depth: 4,
    parentId: 'cx-a-main-start'
  }),
  createTimelineNode({
    id: 'cx-u-visual-dark',
    messageId: 'cx-05d-b',
    title: 'Dark visual alternative',
    description: 'Nested side branch from the visual fork.',
    timestamp: '12:22',
    kind: 'question',
    activeChildId: 'cx-a-visual-dark',
    branchId: 'visual-dark',
    childIds: ['cx-a-visual-dark'],
    depth: 4,
    isOnActivePath: false,
    lane: 4,
    parentId: 'cx-u-visual',
    siblingCount: 3,
    siblingIndex: 1
  }),
  createTimelineNode({
    id: 'cx-u-visual-dense',
    messageId: 'cx-05d-c',
    title: 'Dense visual alternative',
    description: 'Second nested side branch from the visual fork.',
    timestamp: '12:23',
    kind: 'question',
    activeChildId: 'cx-a-visual-dense',
    branchId: 'visual-dense',
    childIds: ['cx-a-visual-dense'],
    depth: 4,
    isOnActivePath: false,
    lane: 5,
    parentId: 'cx-u-visual',
    siblingCount: 3,
    siblingIndex: 2
  }),
  createTimelineNode({
    id: 'cx-a-main-result',
    messageId: 'cx-06',
    title: 'Main branch result',
    description: 'Main path reaches a final answer after many side branches.',
    timestamp: '12:24',
    kind: 'answer',
    activeChildId: 'cx-u-main-wrap',
    childIds: ['cx-u-main-wrap'],
    depth: 5,
    parentId: 'cx-u-main-review'
  }),
  createTimelineNode({
    id: 'cx-u-visual-wrap',
    messageId: 'cx-06d',
    title: 'Visual branch wrap',
    description: 'Nested fork main route continues one more turn.',
    timestamp: '12:25',
    kind: 'question',
    activeChildId: 'cx-a-visual-wrap',
    branchId: 'visual',
    childIds: ['cx-a-visual-wrap'],
    depth: 5,
    isOnActivePath: false,
    lane: 3,
    parentId: 'cx-a-visual-main'
  }),
  createTimelineNode({
    id: 'cx-a-visual-dark',
    messageId: 'cx-06d-b',
    title: 'Dark visual answer',
    description: 'Nested dark alternative ends here.',
    timestamp: '12:26',
    kind: 'answer',
    branchId: 'visual-dark',
    depth: 5,
    isOnActivePath: false,
    lane: 4,
    parentId: 'cx-u-visual-dark'
  }),
  createTimelineNode({
    id: 'cx-a-visual-dense',
    messageId: 'cx-06d-c',
    title: 'Dense visual answer',
    description: 'Nested dense alternative ends here.',
    timestamp: '12:27',
    kind: 'answer',
    branchId: 'visual-dense',
    depth: 5,
    isOnActivePath: false,
    lane: 5,
    parentId: 'cx-u-visual-dense'
  }),
  createTimelineNode({
    id: 'cx-u-main-wrap',
    messageId: 'cx-07',
    title: 'Main branch wrap',
    description: 'Final user turn after the complex fork.',
    timestamp: '12:28',
    kind: 'question',
    activeChildId: 'cx-a-main-final',
    childIds: ['cx-a-main-final'],
    depth: 6,
    parentId: 'cx-a-main-result',
    status: { label: 'Running', state: 'running' }
  }),
  createTimelineNode({
    id: 'cx-a-visual-wrap',
    messageId: 'cx-07d',
    title: 'Visual branch final',
    description: 'The nested visual main branch finishes after several turns.',
    timestamp: '12:29',
    kind: 'answer',
    branchId: 'visual',
    depth: 6,
    isOnActivePath: false,
    lane: 3,
    parentId: 'cx-u-visual-wrap'
  }),
  createTimelineNode({
    id: 'cx-a-main-final',
    messageId: 'cx-08',
    title: 'Complex main final',
    description: 'Main path final answer remains readable despite many sibling lanes.',
    timestamp: '12:30',
    kind: 'answer',
    depth: 7,
    parentId: 'cx-u-main-wrap'
  })
]

export const chatTimelineScenarios = [
  {
    id: 'long-history',
    hostMessageInserts: chatTimelineHostMessageInserts,
    initialNodeId: 'u-git-graph',
    nodes: chatTimelineNodes,
    title: 'Long History'
  },
  {
    id: 'small-data',
    hostMessageInserts: [],
    initialNodeId: 'small-u-start',
    nodes: smallTimelineNodes,
    shellClassName: 'is-small-data',
    title: 'Small Data'
  },
  {
    id: 'complex-forks',
    hostMessageInserts: [],
    initialNodeId: 'cx-u-router',
    nodes: complexForkTimelineNodes,
    shellClassName: 'is-complex-forks',
    title: 'Complex Forks'
  }
]
