import { parseRelayServerArgs } from '../src/config.js'
import type { RelayConfigEnv } from '../src/config.js'
import { createRelayFetchHandler } from '../src/platform/fetch-handler.js'
import { createDurableObjectRelayStoreRepository } from '../src/storage/durable-object.js'
import type { RelayDurableObjectStorage } from '../src/storage/durable-object.js'

interface RelayDurableObjectNamespace {
  get: (id: unknown) => { fetch: (request: Request) => Promise<Response> }
  idFromName: (name: string) => unknown
}

interface RelayCloudflareEnv {
  ONEWORKS_RELAY_ADMIN_TOKEN?: string
  ONEWORKS_RELAY_ALLOW_ORIGIN?: string
  ONEWORKS_RELAY_AVATAR_URL?: string
  ONEWORKS_RELAY_DEVICE_METADATA_SECRET?: string
  ONEWORKS_RELAY_DEVICE_ONLINE_TTL_SECONDS?: string
  ONEWORKS_RELAY_EMAIL_CODE_TTL_SECONDS?: string
  ONEWORKS_RELAY_EMAIL_DISPOSABLE_BLOCKLIST_ENABLED?: string
  ONEWORKS_RELAY_EMAIL_DOMAIN_ALLOWLIST?: string
  ONEWORKS_RELAY_EMAIL_DOMAIN_BLOCKLIST?: string
  ONEWORKS_RELAY_EMAIL_FROM?: string
  ONEWORKS_RELAY_EMAIL_PROVIDER?: string
  ONEWORKS_RELAY_EMAIL_RESEND_COOLDOWN_SECONDS?: string
  ONEWORKS_RELAY_EMAIL_RISK_DAILY_BUDGET?: string
  ONEWORKS_RELAY_EMAIL_RISK_DOMAIN_MAX?: string
  ONEWORKS_RELAY_EMAIL_RISK_DOMAIN_WINDOW_SECONDS?: string
  ONEWORKS_RELAY_EMAIL_RISK_EMAIL_MAX?: string
  ONEWORKS_RELAY_EMAIL_RISK_EMAIL_WINDOW_SECONDS?: string
  ONEWORKS_RELAY_EMAIL_RISK_ENABLED?: string
  ONEWORKS_RELAY_EMAIL_RISK_IP_MAX?: string
  ONEWORKS_RELAY_EMAIL_RISK_IP_WINDOW_SECONDS?: string
  ONEWORKS_RELAY_EMAIL_RISK_MONTHLY_BUDGET?: string
  ONEWORKS_RELAY_EMAIL_TURNSTILE_MODE?: string
  ONEWORKS_RELAY_GITHUB_CLIENT_ID?: string
  ONEWORKS_RELAY_GITHUB_CLIENT_SECRET?: string
  ONEWORKS_RELAY_GOOGLE_CLIENT_ID?: string
  ONEWORKS_RELAY_GOOGLE_CLIENT_SECRET?: string
  ONEWORKS_RELAY_INSTANCE_ID?: string
  ONEWORKS_RELAY_LOGIN_REDIRECT_ORIGINS?: string
  ONEWORKS_RELAY_PUBLIC_URL?: string
  ONEWORKS_RELAY_RESEND_API_KEY?: string
  ONEWORKS_RELAY_SESSION_TTL_SECONDS?: string
  ONEWORKS_RELAY_SSO_PROVIDERS?: string
  ONEWORKS_RELAY_TURNSTILE_SECRET_KEY?: string
  ONEWORKS_RELAY_TURNSTILE_VERIFY_URL?: string
  RELAY_OBJECT: RelayDurableObjectNamespace
}

const envRecord = (env: RelayCloudflareEnv): RelayConfigEnv => ({
  ONEWORKS_RELAY_ADMIN_TOKEN: env.ONEWORKS_RELAY_ADMIN_TOKEN,
  ONEWORKS_RELAY_ALLOW_ORIGIN: env.ONEWORKS_RELAY_ALLOW_ORIGIN,
  ONEWORKS_RELAY_AVATAR_URL: env.ONEWORKS_RELAY_AVATAR_URL,
  ONEWORKS_RELAY_DEVICE_METADATA_SECRET: env.ONEWORKS_RELAY_DEVICE_METADATA_SECRET,
  ONEWORKS_RELAY_DEVICE_ONLINE_TTL_SECONDS: env.ONEWORKS_RELAY_DEVICE_ONLINE_TTL_SECONDS,
  ONEWORKS_RELAY_EMAIL_CODE_TTL_SECONDS: env.ONEWORKS_RELAY_EMAIL_CODE_TTL_SECONDS,
  ONEWORKS_RELAY_EMAIL_DISPOSABLE_BLOCKLIST_ENABLED: env.ONEWORKS_RELAY_EMAIL_DISPOSABLE_BLOCKLIST_ENABLED,
  ONEWORKS_RELAY_EMAIL_DOMAIN_ALLOWLIST: env.ONEWORKS_RELAY_EMAIL_DOMAIN_ALLOWLIST,
  ONEWORKS_RELAY_EMAIL_DOMAIN_BLOCKLIST: env.ONEWORKS_RELAY_EMAIL_DOMAIN_BLOCKLIST,
  ONEWORKS_RELAY_EMAIL_FROM: env.ONEWORKS_RELAY_EMAIL_FROM,
  ONEWORKS_RELAY_EMAIL_PROVIDER: env.ONEWORKS_RELAY_EMAIL_PROVIDER,
  ONEWORKS_RELAY_EMAIL_RESEND_COOLDOWN_SECONDS: env.ONEWORKS_RELAY_EMAIL_RESEND_COOLDOWN_SECONDS,
  ONEWORKS_RELAY_EMAIL_RISK_DAILY_BUDGET: env.ONEWORKS_RELAY_EMAIL_RISK_DAILY_BUDGET,
  ONEWORKS_RELAY_EMAIL_RISK_DOMAIN_MAX: env.ONEWORKS_RELAY_EMAIL_RISK_DOMAIN_MAX,
  ONEWORKS_RELAY_EMAIL_RISK_DOMAIN_WINDOW_SECONDS: env.ONEWORKS_RELAY_EMAIL_RISK_DOMAIN_WINDOW_SECONDS,
  ONEWORKS_RELAY_EMAIL_RISK_EMAIL_MAX: env.ONEWORKS_RELAY_EMAIL_RISK_EMAIL_MAX,
  ONEWORKS_RELAY_EMAIL_RISK_EMAIL_WINDOW_SECONDS: env.ONEWORKS_RELAY_EMAIL_RISK_EMAIL_WINDOW_SECONDS,
  ONEWORKS_RELAY_EMAIL_RISK_ENABLED: env.ONEWORKS_RELAY_EMAIL_RISK_ENABLED,
  ONEWORKS_RELAY_EMAIL_RISK_IP_MAX: env.ONEWORKS_RELAY_EMAIL_RISK_IP_MAX,
  ONEWORKS_RELAY_EMAIL_RISK_IP_WINDOW_SECONDS: env.ONEWORKS_RELAY_EMAIL_RISK_IP_WINDOW_SECONDS,
  ONEWORKS_RELAY_EMAIL_RISK_MONTHLY_BUDGET: env.ONEWORKS_RELAY_EMAIL_RISK_MONTHLY_BUDGET,
  ONEWORKS_RELAY_EMAIL_TURNSTILE_MODE: env.ONEWORKS_RELAY_EMAIL_TURNSTILE_MODE,
  ONEWORKS_RELAY_GITHUB_CLIENT_ID: env.ONEWORKS_RELAY_GITHUB_CLIENT_ID,
  ONEWORKS_RELAY_GITHUB_CLIENT_SECRET: env.ONEWORKS_RELAY_GITHUB_CLIENT_SECRET,
  ONEWORKS_RELAY_GOOGLE_CLIENT_ID: env.ONEWORKS_RELAY_GOOGLE_CLIENT_ID,
  ONEWORKS_RELAY_GOOGLE_CLIENT_SECRET: env.ONEWORKS_RELAY_GOOGLE_CLIENT_SECRET,
  ONEWORKS_RELAY_LOGIN_REDIRECT_ORIGINS: env.ONEWORKS_RELAY_LOGIN_REDIRECT_ORIGINS,
  ONEWORKS_RELAY_PUBLIC_URL: env.ONEWORKS_RELAY_PUBLIC_URL,
  ONEWORKS_RELAY_RESEND_API_KEY: env.ONEWORKS_RELAY_RESEND_API_KEY,
  ONEWORKS_RELAY_SESSION_TTL_SECONDS: env.ONEWORKS_RELAY_SESSION_TTL_SECONDS,
  ONEWORKS_RELAY_SSO_PROVIDERS: env.ONEWORKS_RELAY_SSO_PROVIDERS,
  ONEWORKS_RELAY_TURNSTILE_SECRET_KEY: env.ONEWORKS_RELAY_TURNSTILE_SECRET_KEY,
  ONEWORKS_RELAY_TURNSTILE_VERIFY_URL: env.ONEWORKS_RELAY_TURNSTILE_VERIFY_URL
})

const argsFromEnv = (env: RelayCloudflareEnv) => ({
  ...parseRelayServerArgs([], envRecord(env)),
  dataPath: 'cloudflare-durable-object',
  embeddedAdminUi: false,
  host: '0.0.0.0',
  port: 0,
  storageDriver: 'cloudflare-do' as const
})

export class RelayDurableObject {
  private readonly handler: (request: Request) => Promise<Response>

  constructor(state: { storage: RelayDurableObjectStorage }, env: RelayCloudflareEnv) {
    this.handler = createRelayFetchHandler(argsFromEnv(env), {
      storeRepository: createDurableObjectRelayStoreRepository(state.storage)
    })
  }

  async fetch(request: Request) {
    return await this.handler(request)
  }
}

export default {
  async fetch(request: Request, env: RelayCloudflareEnv) {
    const id = env.RELAY_OBJECT.idFromName(env.ONEWORKS_RELAY_INSTANCE_ID ?? 'main')
    return await env.RELAY_OBJECT.get(id).fetch(request)
  }
}
