#include "authority-handle.h"
#include <exception>
#include <utility>
#include "napi-util.h"
namespace owfs { namespace { struct AuthorityHolder { std::unique_ptr<Authority> authority; }; void FinalizeAuthority(napi_env, void* data, void*) { delete static_cast<AuthorityHolder*>(data); }
napi_value CloseAuthority(napi_env env, napi_callback_info info) { try { std::size_t argc = 1; napi_value argv[1]; Check(env, napi_get_cb_info(env, info, &argc, argv, nullptr, nullptr), "close args"); if (argc != 1) throw AuthorityError("asset_native_protocol_error", "close authority expects one handle"); auto* holder = static_cast<AuthorityHolder*>(TaggedExternal(env, argv[0], kAuthorityTypeTag)); holder->authority.reset(); napi_value result; Check(env, napi_get_undefined(env, &result), "close authority result"); return result; } catch (const AuthorityError& error) { ThrowJs(env, error.code, error.what()); } catch (const std::exception& error) { ThrowJs(env, "asset_filesystem_authority_unavailable", error.what()); } return nullptr; } }
napi_value CreateAuthorityHandle(napi_env env, std::unique_ptr<Authority> authority) { auto holder = std::make_unique<AuthorityHolder>(); holder->authority = std::move(authority); napi_value external; Check(env, napi_create_external(env, holder.get(), FinalizeAuthority, nullptr, &external), "authority handle"); holder.release(); TagObject(env, external, kAuthorityTypeTag); return external; }
Authority* AuthorityFromHandle(napi_env env, napi_value value) { auto* holder = static_cast<AuthorityHolder*>(TaggedExternal(env, value, kAuthorityTypeTag)); if (holder->authority == nullptr) throw AuthorityError("asset_filesystem_authority_unavailable", "native authority is closed"); return holder->authority.get(); }
void ExportAuthorityClose(napi_env env, napi_value exports) { napi_value close; Check(env, napi_create_function(env, "closeAuthority", NAPI_AUTO_LENGTH, CloseAuthority, nullptr, &close), "close authority export"); Check(env, napi_set_named_property(env, exports, "closeAuthority", close), "set close authority"); } }
