#include <node_api.h>
#include <exception>
#include <memory>
#include <thread>
#include "authority.h"
#include "authority-handle.h"
#include "napi-util.h"
#include "peer.h"
namespace owfs { namespace {
napi_value Open(napi_env env, napi_callback_info info) { try { std::size_t argc = 2; napi_value argv[2]; Check(env, napi_get_cb_info(env, info, &argc, argv, nullptr, nullptr), "open args"); if (argc != 2) throw AuthorityError("asset_native_protocol_error", "open expects two paths"); auto authority = OpenPlatformAuthority(JsString(env, argv[0]), JsString(env, argv[1])); const std::string authority_id = authority->id(); const std::string capability = authority->capability(); napi_value object; Check(env, napi_create_object(env, &object), "authority object"); napi_value external = CreateAuthorityHandle(env, std::move(authority)); Check(env, napi_set_named_property(env, object, "handle", external), "set authority handle"); Check(env, napi_set_named_property(env, object, "id", JsStringValue(env, authority_id)), "set authority id"); Check(env, napi_set_named_property(env, object, "capability", JsStringValue(env, capability)), "set capability"); return object; } catch (const AuthorityError& error) { ThrowJs(env, error.code, error.what()); } catch (const std::exception& error) { ThrowJs(env, "asset_filesystem_authority_unavailable", error.what()); } return nullptr; }
PublishRequest ReadPublishRequest(napi_env env, std::size_t argc, napi_value* argv) { if (argc < 6) throw AuthorityError("asset_native_protocol_error", "publish expects six arguments"); PublishRequest request{}; request.authority_id = JsString(env, argv[1]); request.parent_segments = JsStringArray(env, argv[2]); request.basename = JsString(env, argv[3]); request.bytes = JsBytes(env, argv[4]); request.nonce = JsString(env, argv[5]); if (argc == 7) request.fault = JsOptionalString(env, argv[6], "fault"); ValidateRequest(request); return request; }
napi_value Publish(napi_env env, napi_callback_info info) { try { std::size_t argc = 7; napi_value argv[7]; Check(env, napi_get_cb_info(env, info, &argc, argv, nullptr, nullptr), "publish args"); auto* authority = AuthorityFromHandle(env, argv[0]); PublishRequest request = ReadPublishRequest(env, argc, argv); if (request.authority_id != authority->id()) return JsPublishResult(env, Failure("asset_destination_changed")); PublishResult result; std::exception_ptr failure; std::thread worker([&] { try { result = authority->Publish(request); } catch (...) { failure = std::current_exception(); } }); worker.join(); if (failure != nullptr) std::rethrow_exception(failure); return JsPublishResult(env, result); } catch (const AuthorityError& error) { return JsPublishResult(env, Failure(error.code)); } catch (const std::exception&) { return JsPublishResult(env, Failure("asset_filesystem_authority_unavailable")); } }
napi_value VerifyPeer(napi_env env, napi_callback_info info) { try { std::size_t argc = 2; napi_value argv[2]; Check(env, napi_get_cb_info(env, info, &argc, argv, nullptr, nullptr), "peer args"); if (argc != 2) throw AuthorityError("asset_native_protocol_error", "peer expects descriptor and role"); std::int64_t descriptor = -1; bool server_side = false; Check(env, napi_get_value_int64(env, argv[0], &descriptor), "peer descriptor"); Check(env, napi_get_value_bool(env, argv[1], &server_side), "peer role"); napi_value result; Check(env, napi_get_boolean(env, descriptor >= 0 && VerifyLocalPeer(static_cast<std::uint64_t>(descriptor), server_side), &result), "peer result"); return result; } catch (const std::exception&) { napi_value result; napi_get_boolean(env, false, &result); return result; } }
napi_value Initialize(napi_env env, napi_value exports) { napi_value open; napi_value publish; napi_value verify_peer; Check(env, napi_create_function(env, "openAuthority", NAPI_AUTO_LENGTH, Open, nullptr, &open), "open export"); Check(env, napi_create_function(env, "publishSync", NAPI_AUTO_LENGTH, Publish, nullptr, &publish), "publish export"); Check(env, napi_create_function(env, "verifyLocalPeer", NAPI_AUTO_LENGTH, VerifyPeer, nullptr, &verify_peer), "peer export"); Check(env, napi_set_named_property(env, exports, "openAuthority", open), "set open"); Check(env, napi_set_named_property(env, exports, "publishSync", publish), "set publish"); ExportAuthorityClose(env, exports); Check(env, napi_set_named_property(env, exports, "verifyLocalPeer", verify_peer), "set peer"); return exports; }
} }
NAPI_MODULE_INIT() { return owfs::Initialize(env, exports); }
