#include "authority.h"
#include <chrono>
#include <cstdlib>
#include <regex>
#include <thread>
namespace owfs { namespace { bool InvalidSegment(const std::string& value) { if (value.empty() || value == "." || value == ".." || value.size() > 255) return true; for (const unsigned char byte : value) if (byte < 0x20 || byte == 0x7f || byte == '/' || byte == '\\') return true; return false; } }
void ValidateRequest(const PublishRequest& request) { if (request.authority_id.empty() || request.parent_segments.empty() || request.parent_segments.size() > 32) throw AuthorityError("asset_native_protocol_error", "Invalid authority request"); for (const auto& segment : request.parent_segments) if (InvalidSegment(segment)) throw AuthorityError("asset_destination_forbidden", "Invalid parent segment"); if (InvalidSegment(request.basename) || request.basename.size() < 4 || request.basename.substr(request.basename.size() - 3) != ".md") throw AuthorityError("asset_destination_forbidden", "Invalid asset basename"); if (request.bytes.size() > 256 * 1024) throw AuthorityError("asset_native_protocol_error", "Asset content is too large"); if (!std::regex_match(request.nonce, std::regex("^[a-f0-9]{32}$"))) throw AuthorityError("asset_native_protocol_error", "Invalid staging nonce"); }
void ValidateTreeRequest(const TreeRequest& request) { if (request.authority_id.empty() || request.parent_segments.empty() || request.parent_segments.size() > 32) throw AuthorityError("asset_native_protocol_error", "Invalid tree authority request"); for (const auto& segment : request.parent_segments) if (InvalidSegment(segment)) throw AuthorityError("managed_tree_changed", "Invalid tree parent segment"); if (InvalidSegment(request.entry_name)) throw AuthorityError("managed_tree_changed", "Invalid managed tree entry"); if (request.action != "identify" && (InvalidSegment(request.quarantine_name) || request.expected_parent_identity.empty() || request.expected_identity.empty())) throw AuthorityError("managed_tree_transaction_invalid", "Invalid managed tree transaction"); if (request.action != "identify" && request.action != "stage" && request.action != "restore" && request.action != "remove") throw AuthorityError("managed_tree_transaction_invalid", "Invalid managed tree action"); }
void TestCheckpoint(const PublishRequest& request) { if (request.fault == "crash-after-stage") std::_Exit(86); if (request.fault == "pause-before-publish") std::this_thread::sleep_for(std::chrono::milliseconds(1500)); }
void TestFinalPublishCheckpoint(const PublishRequest& request) { if (request.fault == "pause-after-final-check") std::this_thread::sleep_for(std::chrono::milliseconds(1500)); }
PublishResult Failure(const std::string& code) { PublishResult result{}; result.state = "error"; result.code = code; return result; } PublishResult Committed() { PublishResult result{}; result.state = "committed"; result.committed = true; return result; } PublishResult Degraded(const std::string& warning) { PublishResult result{}; result.state = "committed-degraded"; result.warnings = {warning}; result.committed = true; return result; } PublishResult Indeterminate(const std::string& warning) { PublishResult result{}; result.state = "committed-indeterminate"; result.warnings = {warning}; result.committed = true; result.indeterminate = true; return result; } }
