#include "authority.h"
#include "posix-fd.h"
#include <cerrno>
#include <fcntl.h>
#include <sys/clonefile.h>
#include <sys/stat.h>
#include <unistd.h>
#include <memory>
namespace owfs { namespace {
#ifndef ENOTCAPABLE
constexpr int kNotCapable = 107;
#else
constexpr int kNotCapable = ENOTCAPABLE;
#endif
int OpenComponent(int parent, const std::string& name, int flags, mode_t mode = 0) { return openat(parent, name.c_str(), flags | O_CLOEXEC | O_NOFOLLOW_ANY, mode); }
PublishResult WithErrno(PublishResult result, const char* operation, int error) { result.warnings.push_back(std::string("darwin:") + operation + ":errno=" + std::to_string(error)); return result; }
PublishResult ErrorFor(const char* operation, int error) { if (error == EEXIST || error == EXDEV || error == ENOTSUP || error == kNotCapable || error == EINVAL) return WithErrno(Failure("asset_filesystem_authority_unavailable"), operation, error); if (error == ELOOP || error == ENOENT || error == ENOTDIR) return WithErrno(Failure("asset_destination_changed"), operation, error); return WithErrno(Failure("asset_destination_forbidden"), operation, error); }
UniqueFd OpenParent(int root, const PublishRequest& request, bool create, PublishResult* failure) { UniqueFd current(fcntl(root, F_DUPFD_CLOEXEC, 0)); if (!current) { *failure = ErrorFor("fcntl-root-dup", errno); return UniqueFd(-1); } for (const auto& segment : request.parent_segments) { UniqueFd next(OpenComponent(current.get(), segment, O_RDONLY | O_DIRECTORY)); if (!next && errno == ENOENT && create) { if (mkdirat(current.get(), segment.c_str(), 0755) != 0 && errno != EEXIST) { *failure = ErrorFor("mkdirat-parent", errno); return UniqueFd(-1); } next = UniqueFd(OpenComponent(current.get(), segment, O_RDONLY | O_DIRECTORY)); } if (!next) { *failure = ErrorFor("openat-parent", errno); return UniqueFd(-1); } current = std::move(next); } return current; }
class DarwinAuthority final : public Authority { public: DarwinAuthority(UniqueFd root, UniqueFd control) : root_(std::move(root)), control_(std::move(control)), id_(PosixAuthorityId(root_.get())) {} const std::string& id() const override { return id_; } const std::string& capability() const override { return capability_; } PublishResult Publish(const PublishRequest& request) override; private: UniqueFd root_; UniqueFd control_; std::string id_; std::string capability_ = "darwin-fclone-beneath-v1"; };
PublishResult DarwinAuthority::Publish(const PublishRequest& request) { PublishResult failure; UniqueFd checked_parent(OpenParent(root_.get(), request, true, &failure)); if (!checked_parent) return failure; const std::string stage_name = request.nonce + ".stage"; UniqueFd stage(OpenComponent(checked_parent.get(), stage_name, O_CREAT | O_EXCL | O_RDWR, 0600)); if (!stage) return ErrorFor("openat-stage", errno); if (unlinkat(checked_parent.get(), stage_name.c_str(), 0) != 0) return ErrorFor("unlinkat-stage", errno); if (!WriteAll(stage.get(), request.bytes)) return ErrorFor("write-stage", errno); if (fchmod(stage.get(), 0644) != 0 || fsync(stage.get()) != 0 || fcntl(stage.get(), F_FULLFSYNC) != 0 || request.fault == "file-sync") return Failure("asset_filesystem_authority_unavailable"); TestCheckpoint(request); UniqueFd verified_parent(OpenParent(root_.get(), request, false, &failure)); if (!verified_parent) return failure; struct stat checked_info {}; struct stat verified_info {}; if (fstat(checked_parent.get(), &checked_info) != 0 || fstat(verified_parent.get(), &verified_info) != 0) return ErrorFor("fstat-parent", errno); if (checked_info.st_dev != verified_info.st_dev || checked_info.st_ino != verified_info.st_ino) return Failure("asset_destination_changed"); struct stat existing {}; if (fstatat(verified_parent.get(), request.basename.c_str(), &existing, AT_SYMLINK_NOFOLLOW) == 0) return Failure("asset_exists"); if (errno != ENOENT) return ErrorFor("fstatat-target", errno); TestFinalPublishCheckpoint(request); if (fclonefileat(stage.get(), verified_parent.get(), request.basename.c_str(), CLONE_NOFOLLOW_ANY) != 0) { const int error = errno; if (error == EEXIST) return WithErrno(Failure("asset_exists"), "fclonefileat", error); return ErrorFor("fclonefileat", error); } if (request.fault == "identity-probe") return Indeterminate("asset_target_identity_unconfirmed"); UniqueFd target_fd(OpenComponent(verified_parent.get(), request.basename, O_RDONLY)); if (!target_fd || !MatchesRegularFile(target_fd.get(), request.bytes) || fsync(target_fd.get()) != 0) return Indeterminate("asset_target_sync_indeterminate"); if (request.fault == "parent-sync") return Indeterminate("asset_parent_sync_indeterminate"); if (fsync(verified_parent.get()) != 0) { if (errno == EINVAL || errno == ENOTSUP) return Degraded("asset_parent_fsync_unsupported"); return Indeterminate("asset_parent_sync_indeterminate"); } return Committed(); }
} std::unique_ptr<Authority> OpenPlatformAuthority(const std::string& workspace_root, const std::string& control_root) { UniqueFd root(open(workspace_root.c_str(), O_RDONLY | O_DIRECTORY | O_CLOEXEC | O_NOFOLLOW_ANY)); UniqueFd control(open(control_root.c_str(), O_RDONLY | O_DIRECTORY | O_CLOEXEC | O_NOFOLLOW_ANY)); if (!root || !control || PosixAuthorityId(root.get()).empty()) throw AuthorityError("asset_filesystem_authority_unavailable", "Filesystem authority root is unavailable"); return std::make_unique<DarwinAuthority>(std::move(root), std::move(control)); } }
