#include "napi-util.h"
#include <limits>
namespace owfs { const napi_type_tag kAuthorityTypeTag{0xb5a4f2954ba9cd10ULL, 0x8f0bd0643c4bd8d7ULL};
void Check(napi_env env, napi_status status, const char* operation) { if (status == napi_ok) return; const napi_extended_error_info* info = nullptr; napi_get_last_error_info(env, &info); throw AuthorityError("asset_native_protocol_error", std::string(operation) + ": " + (info == nullptr ? "N-API error" : info->error_message)); }
void TagObject(napi_env env, napi_value value, const napi_type_tag& tag) { Check(env, napi_type_tag_object(env, value, &tag), "native handle tag"); }
void* TaggedExternal(napi_env env, napi_value value, const napi_type_tag& tag) { bool matches = false; Check(env, napi_check_object_type_tag(env, value, &tag, &matches), "native handle type"); if (!matches) throw AuthorityError("asset_native_protocol_error", "native handle type mismatch"); void* raw = nullptr; Check(env, napi_get_value_external(env, value, &raw), "native handle value"); if (raw == nullptr) throw AuthorityError("asset_filesystem_authority_unavailable", "native handle is closed"); return raw; }
std::string JsString(napi_env env, napi_value value) { std::size_t size = 0; Check(env, napi_get_value_string_utf8(env, value, nullptr, 0, &size), "string size"); std::string result(size, '\0'); Check(env, napi_get_value_string_utf8(env, value, result.data(), size + 1, &size), "string value"); return result; }
std::vector<std::uint8_t> JsBytes(napi_env env, napi_value value) { void* data = nullptr; std::size_t size = 0; Check(env, napi_get_buffer_info(env, value, &data, &size), "buffer value"); const auto* bytes = static_cast<const std::uint8_t*>(data); return {bytes, bytes + size}; }
std::vector<std::string> JsStringArray(napi_env env, napi_value value) { bool is_array = false; Check(env, napi_is_array(env, value, &is_array), "array check"); if (!is_array) throw AuthorityError("asset_native_protocol_error", "Expected array"); std::uint32_t length = 0; Check(env, napi_get_array_length(env, value, &length), "array length"); std::vector<std::string> result; result.reserve(length); for (std::uint32_t index = 0; index < length; ++index) { napi_value item; Check(env, napi_get_element(env, value, index, &item), "array item"); result.push_back(JsString(env, item)); } return result; }
std::string JsOptionalString(napi_env env, napi_value object, const char* name) { napi_valuetype type; Check(env, napi_typeof(env, object, &type), "option type"); if (type != napi_object) return {}; bool present = false; Check(env, napi_has_named_property(env, object, name, &present), "option check"); if (!present) return {}; napi_value value; Check(env, napi_get_named_property(env, object, name, &value), "option value"); return JsString(env, value); }
napi_value JsStringValue(napi_env env, const std::string& value) { napi_value result; Check(env, napi_create_string_utf8(env, value.data(), value.size(), &result), "create string"); return result; }
void ThrowJs(napi_env env, const std::string& code, const std::string& message) { napi_value error; Check(env, napi_create_error(env, nullptr, JsStringValue(env, message), &error), "create error"); Check(env, napi_set_named_property(env, error, "code", JsStringValue(env, code)), "error code"); napi_throw(env, error); }
napi_value JsPublishResult(napi_env env, const PublishResult& result) { napi_value object; Check(env, napi_create_object(env, &object), "create result"); Check(env, napi_set_named_property(env, object, "state", JsStringValue(env, result.state)), "result state"); if (!result.code.empty()) Check(env, napi_set_named_property(env, object, "code", JsStringValue(env, result.code)), "result code"); if (!result.parent_identity.empty()) Check(env, napi_set_named_property(env, object, "parentIdentity", JsStringValue(env, result.parent_identity)), "parent identity"); if (!result.identity.empty()) Check(env, napi_set_named_property(env, object, "identity", JsStringValue(env, result.identity)), "result identity"); napi_value committed; if (result.indeterminate) committed = JsStringValue(env, "indeterminate"); else Check(env, napi_get_boolean(env, result.committed, &committed), "committed value"); Check(env, napi_set_named_property(env, object, "committed", committed), "committed"); if (result.warnings.size() > std::numeric_limits<std::uint32_t>::max()) throw AuthorityError("asset_native_protocol_error", "Too many native warnings"); napi_value warnings; Check(env, napi_create_array_with_length(env, result.warnings.size(), &warnings), "warnings"); for (std::size_t index = 0; index < result.warnings.size(); ++index) Check(env, napi_set_element(env, warnings, static_cast<std::uint32_t>(index), JsStringValue(env, result.warnings[index])), "warning"); Check(env, napi_set_named_property(env, object, "warnings", warnings), "warnings value"); return object; } }
